# Generated by Django 5.1.6 on 2025-02-27 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlastFurnaceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cold_blast_pressure', models.FloatField(blank=True, null=True)),
                ('hot_blast_pressure', models.FloatField(blank=True, null=True)),
                ('cold_blast_flow', models.FloatField(blank=True, null=True)),
                ('hot_blast_flow', models.FloatField(blank=True, null=True)),
                ('hot_blast_temperature', models.FloatField(blank=True, null=True)),
                ('raft', models.FloatField(blank=True, null=True)),
                ('new_calc', models.FloatField(blank=True, null=True)),
                ('top_pressure', models.FloatField(blank=True, null=True)),
                ('d_pressure_burden', models.FloatField(blank=True, null=True)),
                ('discharge_level', models.FloatField(blank=True, null=True)),
                ('current_burden_level', models.FloatField(blank=True, null=True)),
                ('moisture_in_hot_blast', models.FloatField(blank=True, null=True)),
                ('coal_injection_rate_kg', models.FloatField(blank=True, null=True)),
                ('coal_injection_rate_ton', models.FloatField(blank=True, null=True)),
                ('sp', models.FloatField(blank=True, null=True)),
                ('oxygen_injection', models.FloatField(blank=True, null=True)),
                ('top_dp', models.FloatField(blank=True, null=True)),
                ('mid_dp', models.FloatField(blank=True, null=True)),
                ('bottom_dp', models.FloatField(blank=True, null=True)),
                ('bottom_k_mid_k', models.FloatField(blank=True, null=True)),
                ('permeability_k_sum', models.FloatField(blank=True, null=True)),
                ('charge_per_shift_a', models.FloatField(blank=True, null=True)),
                ('charge_per_shift_b', models.FloatField(blank=True, null=True)),
                ('charge_per_shift_c', models.FloatField(blank=True, null=True)),
                ('hot_metal_temp_th1', models.FloatField(blank=True, null=True)),
                ('hot_metal_temp_th2', models.FloatField(blank=True, null=True)),
                ('hot_metal_temp_th3', models.FloatField(blank=True, null=True)),
                ('hot_metal_temp_th4', models.FloatField(blank=True, null=True)),
                ('uptake_temp_a', models.FloatField(blank=True, null=True)),
                ('uptake_temp_b', models.FloatField(blank=True, null=True)),
                ('uptake_temp_c', models.FloatField(blank=True, null=True)),
                ('uptake_temp_d', models.FloatField(blank=True, null=True)),
                ('tuyere_cooling_flow', models.FloatField(blank=True, null=True)),
                ('tuyere_cooling_pressure', models.FloatField(blank=True, null=True)),
                ('stack_cooling_flow', models.FloatField(blank=True, null=True)),
                ('stack_cooling_pressure', models.FloatField(blank=True, null=True)),
                ('hearth_bottom_flow', models.FloatField(blank=True, null=True)),
                ('hearth_bottom_pressure', models.FloatField(blank=True, null=True)),
                ('secondary_cooling_flow', models.FloatField(blank=True, null=True)),
                ('secondary_cooling_pressure', models.FloatField(blank=True, null=True)),
                ('blt_cooling_flow', models.FloatField(blank=True, null=True)),
                ('heat_load_stack', models.FloatField(blank=True, null=True)),
                ('heat_load_tuyere', models.FloatField(blank=True, null=True)),
                ('heat_load_hearth', models.FloatField(blank=True, null=True)),
                ('feed_tank_1', models.FloatField(blank=True, null=True)),
                ('feed_tank_2', models.FloatField(blank=True, null=True)),
                ('feed_tank_3', models.FloatField(blank=True, null=True)),
                ('fcs_weight', models.FloatField(blank=True, null=True)),
                ('rcs_1_weight', models.FloatField(blank=True, null=True)),
                ('rcs_2_weight', models.FloatField(blank=True, null=True)),
                ('pci_n2_supply_pressure', models.FloatField(blank=True, null=True)),
                ('inst_supply_pressure', models.FloatField(blank=True, null=True)),
                ('lances_on_coal', models.IntegerField(blank=True, null=True)),
                ('hmt_production', models.FloatField(blank=True, null=True)),
                ('low_pressure_n2', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
