# Generated by Django 5.1.6 on 2025-02-27 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPCDashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlastFurnace_BlastFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hot_metal_temp_th1', models.FloatField(blank=True, null=True)),
                ('hot_metal_temp_th2', models.FloatField(blank=True, null=True)),
                ('hot_metal_temp_th3', models.FloatField(blank=True, null=True)),
                ('hot_metal_temp_th4', models.FloatField(blank=True, null=True)),
                ('uptake_temp_a', models.FloatField(blank=True, null=True)),
                ('uptake_temp_b', models.FloatField(blank=True, null=True)),
                ('uptake_temp_c', models.FloatField(blank=True, null=True)),
                ('uptake_temp_d', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlastFurnace_CPP_PCI_Weights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_tank_1', models.FloatField(blank=True, null=True)),
                ('pci_n2_supply_pr', models.FloatField(blank=True, null=True)),
                ('feed_tank_2', models.FloatField(blank=True, null=True)),
                ('inst_supply_pr', models.FloatField(blank=True, null=True)),
                ('feed_tank_3', models.FloatField(blank=True, null=True)),
                ('lances_on_coal', models.IntegerField(blank=True, null=True)),
                ('fcs_weight', models.FloatField(blank=True, null=True)),
                ('hmt_production', models.FloatField(blank=True, null=True)),
                ('rcs_1_wt', models.FloatField(blank=True, null=True)),
                ('rcs_2_wt', models.FloatField(blank=True, null=True)),
                ('low_pressure_n2', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlastFurnace_TemperatureData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tuyere_cooling_1', models.FloatField(blank=True, null=True)),
                ('tuyere_cooling_2', models.FloatField(blank=True, null=True)),
                ('stack_cooling_flow', models.FloatField(blank=True, null=True)),
                ('stack_cooling_pressure', models.FloatField(blank=True, null=True)),
                ('hearth_bottom_flow', models.FloatField(blank=True, null=True)),
                ('hearth_bottom_pressure', models.FloatField(blank=True, null=True)),
                ('secondary_cooling_flow', models.FloatField(blank=True, null=True)),
                ('secondary_cooling_pressure', models.FloatField(blank=True, null=True)),
                ('blt_cooling_flow', models.FloatField(blank=True, null=True)),
                ('blt_cooling_pressure', models.FloatField(blank=True, null=True)),
                ('heat_load_stack', models.FloatField(blank=True, null=True)),
                ('heat_load_tuyere', models.FloatField(blank=True, null=True)),
                ('heat_load_hearth', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='blastfurnacedata',
            old_name='blt_cooling_flow',
            new_name='burden_level',
        ),
        migrations.RenameField(
            model_name='blastfurnacedata',
            old_name='bottom_dp',
            new_name='charge_A',
        ),
        migrations.RenameField(
            model_name='blastfurnacedata',
            old_name='bottom_k_mid_k',
            new_name='charge_B',
        ),
        migrations.RenameField(
            model_name='blastfurnacedata',
            old_name='charge_per_shift_a',
            new_name='charge_C',
        ),
        migrations.RenameField(
            model_name='blastfurnacedata',
            old_name='charge_per_shift_b',
            new_name='coal_injection_rate',
        ),
        migrations.RemoveField(
            model_name='blastfurnacedata',
            name='charge_per_shift_c',
        ),
        migrations.RemoveField(
            model_name='blastfurnacedata',
            name='coal_injection_rate_kg',
        ),
        migrations.RemoveField(
            model_name='blastfurnacedata',
            name='coal_injection_rate_ton',
        ),
        migrations.RemoveField(
            model_name='blastfurnacedata',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='blastfurnacedata',
            name='current_burden_level',
        ),
        migrations.RemoveField(
            model_name='blastfurnacedata',
            name='d_pressure_burden',
        ),
        migrations.RemoveField(
            model_name='blastfurnacedata',
            name='fcs_weight',
        ),
        migrations.RemoveField(
            model_name='blastfurnacedata',
            name='feed_tank_1',
        ),
        migrations.RemoveField(
            model_name='blastfurnacedata',
            name='feed_tank_2',
        ),
        migrations.RemoveField(
            model_name='blastfurnacedata',
            name='feed_tank_3',
        ),
        migrations.RemoveField(
            model_name='blastfurnacedata',
            name='hearth_bottom_flow',
        ),
        migrations.RemoveField(
            model_name='blastfurnacedata',
            name='hearth_bottom_pressure',
        ),
        migrations.RemoveField(
            model_name='blastfurnacedata',
            name='heat_load_hearth',
        ),
        migrations.RemoveField(
            model_name='blastfurnacedata',
            name='heat_load_stack',
        ),
        migrations.RemoveField(
            model_name='blastfurnacedata',
            name='heat_load_tuyere',
        ),
        migrations.RemoveField(
            model_name='blastfurnacedata',
            name='hmt_production',
        ),
        migrations.RemoveField(
            model_name='blastfurnacedata',
            name='hot_metal_temp_th1',
        ),
        migrations.RemoveField(
            model_name='blastfurnacedata',
            name='hot_metal_temp_th2',
        ),
        migrations.RemoveField(
            model_name='blastfurnacedata',
            name='hot_metal_temp_th3',
        ),
        migrations.RemoveField(
            model_name='blastfurnacedata',
            name='hot_metal_temp_th4',
        ),
        migrations.RemoveField(
            model_name='blastfurnacedata',
            name='inst_supply_pressure',
        ),
        migrations.RemoveField(
            model_name='blastfurnacedata',
            name='lances_on_coal',
        ),
        migrations.RemoveField(
            model_name='blastfurnacedata',
            name='low_pressure_n2',
        ),
        migrations.RemoveField(
            model_name='blastfurnacedata',
            name='mid_dp',
        ),
        migrations.RemoveField(
            model_name='blastfurnacedata',
            name='moisture_in_hot_blast',
        ),
        migrations.RemoveField(
            model_name='blastfurnacedata',
            name='pci_n2_supply_pressure',
        ),
        migrations.RemoveField(
            model_name='blastfurnacedata',
            name='permeability_k_sum',
        ),
        migrations.RemoveField(
            model_name='blastfurnacedata',
            name='rcs_1_weight',
        ),
        migrations.RemoveField(
            model_name='blastfurnacedata',
            name='rcs_2_weight',
        ),
        migrations.RemoveField(
            model_name='blastfurnacedata',
            name='secondary_cooling_flow',
        ),
        migrations.RemoveField(
            model_name='blastfurnacedata',
            name='secondary_cooling_pressure',
        ),
        migrations.RemoveField(
            model_name='blastfurnacedata',
            name='sp',
        ),
        migrations.RemoveField(
            model_name='blastfurnacedata',
            name='stack_cooling_flow',
        ),
        migrations.RemoveField(
            model_name='blastfurnacedata',
            name='stack_cooling_pressure',
        ),
        migrations.RemoveField(
            model_name='blastfurnacedata',
            name='top_dp',
        ),
        migrations.RemoveField(
            model_name='blastfurnacedata',
            name='tuyere_cooling_flow',
        ),
        migrations.RemoveField(
            model_name='blastfurnacedata',
            name='tuyere_cooling_pressure',
        ),
        migrations.RemoveField(
            model_name='blastfurnacedata',
            name='uptake_temp_a',
        ),
        migrations.RemoveField(
            model_name='blastfurnacedata',
            name='uptake_temp_b',
        ),
        migrations.RemoveField(
            model_name='blastfurnacedata',
            name='uptake_temp_c',
        ),
        migrations.RemoveField(
            model_name='blastfurnacedata',
            name='uptake_temp_d',
        ),
    ]
